### PR TITLE
add-python-script

### PR DESCRIPTION
**Pull request by alfredomarciano98**
Yang add-jpynb-files abaikan aja pak, apus kalo bisa, rencananya buat yang notebook mau saya buat 1 notebook aja pak lebih bagus.

### CODE REVIEW

**Comment by rafiramadhana** [comment]
ok chill Pak, we can remove it later (my bad didn't read both PR at first...) btw is this final yet? or u still want to add some?

**Comment by alfredomarciano98** [comment]
There's still some, but I prefer to re-learn about DL first before
commenting much in DL part of the program pak

**Comment by rafiramadhana** [comment]
Ok, please let me know if you need help or finished edo86

**Comment by rafiramadhana** [comment]
anyway, is this already working? i think learning DL can be treated as an improvement (so.. at least we have the program works for now, improvement can be done later in another PR), as long as the input and output of our program does not change it is ok from my side, wdyt?

**Review by rafiramadhana — APPROVED** [review]

**Pull request merged**
